language: rust
rust:
  - 1.31.1
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release
  - cargo test --release
  - make api
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then make nightly_api; fi
